name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Unit Tests
        run: ./gradlew test
        
  instrumentation-launch:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8
    strategy:
      # Allow tests to continue on other devices if they fail on one device.
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04 ]
        arch: [ x86_64 ]
        target: [ default, google_apis ]
        channel: [ stable ]
        api-level:
          - 30
        include:
          # - os: ubuntu-24.04-arm
          #   arch: x86_64
          #   api-level: 30
          #   target: aosp_atd
          #   channel: stable
          - os: ubuntu-22.04
            arch: x86_64
            api-level: 30
            target: aosp_atd
            channel: canary
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.os }}-${{ matrix.target }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-load
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          disable-animations: true
          script: |
            touch emulator.log                    # create log file
            chmod 777 emulator.log                # allow writing to log file
            adb logcat >> emulator.log &          # pipe all logcat messages into log file as a background process
            gradle --version
      - name: Upload results
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.api-level }}-${{ matrix.arch }}-${{ matrix.target }}-instrumentation-test-results
          path: |
            emulator.log
            ./**/build/reports/androidTests/connected/**
